### ISSUE TITLE
Create individual CSS files for each Acts Chapter Segment

### ISSUE THREAD

**Issue by EvanZhouDev** [ThatXliner/acts-project#21]
Create individual CSS for each Acts chapter segments so that the CSS doesn’t have to be all in the main stylesheet.

Potential Implementation:
- Simply link stylesheet in the files?

**Comment by ThatXliner** [comment]
We can already put `style` in the same file as the segment (it just needs to come before the segment)

**Comment by EvanZhouDev** [comment]
Appears to be resolved. Closing for now.
