### ISSUE TITLE
Fix overflowing issues.

### ISSUE THREAD

**Issue by EvanZhouDev** [ThatXliner/acts-project#22]
At some browser/window sizes, there is a bit of overflow happening, which disrupts the flow of the scroll.

New issue based on #17... I removed the ```overflow: hidden```, but the code still isn't perfect.

**Comment by EvanZhouDev** [comment]
I believe this is fixed, do we mind closing?

**Comment by DragonXDev** [comment]
I am testing the overflow errors on my MacBook today, so once that checks out we can close.

**Comment by ThatXliner** [comment]
This is fine, right?

**Comment by DragonXDev** [comment]
This is no longer an issue; it was closed.
