### ISSUE TITLE
"Unloading" Scripts From Other Sections

### ISSUE THREAD

**Issue by EvanZhouDev** [ThatXliner/acts-project#28]
Potentially create a bit of logic that unloads scripts that have been loaded from other sections.

## Example of how this can be a bug:
- Switch to Section 1, which loads a script that modifies ```.drawer-content```
- Then I switch to Section 2, which loads *another* script
- If Section 1 has something that is modifying ```.drawer-content```, that will leak into Section 2

## Solutions:
- **Ideal:** "Unloading" the script from section 1 can somehow help
- **Workaround 1:** We can write conditionals to check if we are on a certain page
- **Workaround 2:** Just don't write code that affects something like ```.drawer-content```

Opening this just for you guys to consider.

**Comment by ThatXliner** [comment]
Or we could use Svelte, where all the code is encapsulated already

**Comment by EvanZhouDev** [comment]
This may be resolved by simply being careful with writing code that doesn't impact things that are outside your scope. Please take this into consideration.

**Comment by ThatXliner** [comment]
just curious, do CSS classes leak? like I had a class named as generically as "thing" and you also had an element named of the exact same, would my styles cascade in addition to yours? If so, that will justify using Svelte for once and for all (or we just need a better SPA solution)
