### ISSUE TITLE
Polish Branches

### ISSUE THREAD

**Issue by DragonXDev** [ThatXliner/acts-project#42]
Complete and polish branches:

- [x] Intro
- [x] Acts 1-5
- [x] Acts 6-7 (needs more characters)
- [x] Acts 8-9
- [x] Acts 10-12
- [x] Acts 13-20 (revise text)
- [x] Acts 21-25
- [x] ~~Acts 26-27~~ (Dropped)
- [x] Conclusion

This is for branches that are FINALIZED only and ready for presentation.

**Comment by ThatXliner** [comment]
See also
 - #34

**Comment by DragonXDev** [comment]
Yes but this issue is more general so we can all see a progress update as to which chapters are FULLY done.
